### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Natan7** [wcota/covid19br#12]
Seria interessante acrescentar os casos sob investigação, ou seja, que amostras de sangue foram coletadas mas o resultado do teste ainda não saiu (pelo menos óbitos que estão em teste - EX: https://g1.globo.com/pb/paraiba/noticia/2020/03/23/paraiba-tem-mais-duas-mortes-de-pessoas-com-suspeita-de-coronavirus-segundo-secretaria.ghtml). Muita gente se ilude com esses números e está despreocupada pelo fato de que a doença "ainda não tenha chegado em sua respectiva cidade". Além de tornar o mapeamento da doença um pouco mais preciso.

**Comment by wcota** [comment]
As pessoas que me ajudam com as informações e eu estamos pensando em justamente fazer isso. No entanto, só poderemos fazer isso a nível de estado, por falta de centralização e padrão nos dados divulgados pelas secretarias. Obrigado pela sugestão!

**Comment by wcota** [comment]
Adicionamos (https://github.com/wcota/covid19br/issues/24) o número de casos suspeitos por estado. 
Os por município será difícil por agora, talvez o Brasil.IO passe a fazê-lo mais pra frente. Qualquer novidade por parte deles adicionarei no dataset daqui :)

**Comment by wcota** [comment]
Fechando aqui enquanto não há previsão de colocar informações a mais do que já estão disponíveis. Espero que no futuro a gente possa colocar suspeitos e recuperados por municípios. Quanto aos demais (SRAG e óbitos suspeitos, por exemplo) podem ser vistos no Registro Civil: https://transparencia.registrocivil.org.br/registral-covid
