### ISSUE TITLE
Primeira morte no RS

### ISSUE THREAD

**Issue by w3gaucho** [wcota/covid19br#13]
https://g1.globo.com/rs/rio-grande-do-sul/noticia/2020/03/25/prefeitura-de-porto-alegre-confirma-primeira-morte-por-coronavirus-no-rs.ghtml

**Comment by wcota** [comment]
Muito obrigado pela contribuição!
No entanto, vou atualizar o número de mortes apenas com dados confirmados diretamente pelo Ministério da Saúde, embora as secretarias sejam confiáveis. Se começarem a divergir muito nesses números, essa opção será repensada.

https://github.com/wcota/covid19br/pull/14
