### ISSUE TITLE
Sugestão - Adicionar o código dos municípios dos dados

### ISSUE THREAD

**Issue by hugonbgg** [wcota/covid19br#15]
Meus caros, seria interessante adicionar o código do município aos dados, em uma coluna talvez, assim fica mais fácil fazer a união e cruzamento com outros dados do IBGE como os shapefiles, dados de população, etc. https://www.ibge.gov.br/explica/codigos-dos-municipios.php
O Brasil.io também está fazendo esse mesmo levantamento, talvez fosse interessante vocês conversarem e unirem forças.
Abraços

**Comment by wcota** [comment]
Feito! https://github.com/wcota/covid19br/commit/276ebada6ac0f306368774cfb360862bbe9be2fb
