### ISSUE TITLE
Problema no eixo X do gráfico de R0

### ISSUE THREAD

**Issue by patrickelectric** [wcota/covid19br#19]
![image](https://user-images.githubusercontent.com/1215497/77959454-fb0b8900-72ac-11ea-8b92-864a9fa9c9c9.png)
Aparenta estar mostrando em horas e não em dias.

**Comment by dsevero** [comment]
Mas isso veio de onde?

**Comment by dsevero** [comment]
@wcota pode fechar, tem a ver com o simulador em https://github.com/3778/COVID-19

mais detalhes em https://github.com/3778/COVID-19/issues/89
