### ISSUE TITLE
CSV oficial do covid.saude.gov.br

### ISSUE THREAD

**Issue by dsevero** [wcota/covid19br#20]
Eles botaram um CSV pra download (FINALMENTE) dos dados no site oficial do governo: https://covid.saude.gov.br/

só bater nessa url: https://covid.saude.gov.br/assets/files/BRnCov19_30032020.csv

tem que ver se não vai mudar o link amanhã @wcota 

porém, ainda é **apenas por estado**

**Comment by wcota** [comment]
Muito obrigado! Finalmente fizeram isso.
