### ISSUE TITLE
Inclusão de coluna 'deaths' em outros arquivos

### ISSUE THREAD

**Issue by gabrielrbarbosa** [wcota/covid19br#22]
É possível incluir a coluna de **casos fatais por cidades** para os seguintes arquivos?
gps_cities.csv
cases-brazil-cities-time.csv
O segundo precisaria dos dados por data né mas se for possível incluir no primeiro arquivo.
Obrigado.

**Comment by wcota** [comment]
Olá! No `gps_cities.csv` já tem, são aqueles com `type = D0` ou `D1`. Ainda tenho de documentar isso :(

Colocarei em breve também em função do tempo.

Obrigado!

**Comment by Gabplay** [comment]
Coloquei uma condição pra quando tiver a coluna mostrar o gráfico igual mostro dos estados!

Se quiser testar o app que estou fazendo (pra Android) já tá bem legal olha ai:

https://github.com/Gabplay/flutter_covid19_brasil/blob/master/app-release.apk

**Comment by wcota** [comment]
Feito! Agora os dados de óbitos estão disponíveis tanto para os estados quanto para os municípios, inclusive a quantidade de novos óbitos por dia.
