### ISSUE TITLE
Qual é a Licença? Gostaria de permissão para usar em nosso site

### ISSUE THREAD

**Issue by WittmannF** [wcota/covid19br#23]
Temos um site com relatórios criados a partir de jupyters https://covid19graficos.github.io/ gostaria da permissão para utilizar os seus dados. Atualmente utilizamos o Brasil.io mas há dados ausentes em algumas datas.

**Comment by dsevero** [comment]
A licença é Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).

Ta escrito no README so repositório

**Comment by WittmannF** [comment]
Recomendo também criar um arquivo LICENSE para "oficializar"

**Comment by wcota** [comment]
Realmente antes não tinha especificado a licença e só depois coloquei no README. "Oficializei" lá também: https://github.com/wcota/covid19br/commit/d8937bd95f4b6282c1c863af0d780f477cbfb26f

Obrigado!

**Comment by WittmannF** [comment]
obrigado @wcota ! parabéns pelo trabalho!
