### ISSUE TITLE
Número de recuperações e de suspeitos

### ISSUE THREAD

**Issue by w3gaucho** [wcota/covid19br#24]
Tem como adicionar o número de recuperações e suspeitos do arquivo abaixo no CSV dos casos por estado ou em outro CSV? Criei o site https://mapacoronavirusbrasil.com/ com os seus dados e achei interessante exibir também esses dados. 

https://docs.google.com/spreadsheets/d/1MWQE3s4ef6dxJosyqvsFaV4fDyElxnBUB6gMGvs3rEc/edit#gid=1503196283

**Comment by wcota** [comment]
Coloquei o número de recuperados: https://github.com/wcota/covid19br/commit/8a7af041f39d3b1a14e74b66b52ceebb06d79b45

O de suspeitos talvez coloque, o problema é a falta de dados recentes de algumas secretarias, como SP, RJ, RS, ES, e outras.

**Comment by yjmenezes** [comment]
@wcota , obrigado por seu trabalho.

1- algum estado esta disponibilizando *recuperados, por municipio  ?
2- estou jogando os dados em DB Postgresql+Postgis
3- No DB, criei tabelas com populacao e posicionamento em forma de ponto e de poligono dos 5507 municipios, fonte IBGE.  ( tabela brasil e tabelas mueUF.   www.cartognu.org  )

[]s
julio

**Comment by w3gaucho** [comment]
@wcota boa! comparei os dados da planilha com os da [página da SES-RS](http://ti.saude.rs.gov.br/covid19/) e eles estão um pouco atrasado sim, porém os da SES-RS parecem mais recentes: atualmente (28abr2020 10:17am) na página da SES-RS aparecem 784 recuperados enquanto na planilha aparecem apenas 730

@yjmenezes na [página da SES-RS](http://ti.saude.rs.gov.br/covid19/) só aparecem o número de casos confirmados e de óbitos por município. seria possível fazer uma busca manual dos dados coletados em páginas de notícias locais, mas isso levaria um bom tempo...

achei interessante a utilização de polígonos no leaflet, estou usando arquivos .kml mas eles só mostram o contorno dos estados, será que tem como transformar os .kml em polígonos clicáveis usando os seus dados? se você souber como faz por favor [escreva na issue](https://github.com/MapaCoronavirus/mapacoronavirus.github.io/issues/1), obrigado.

**Comment by yjmenezes** [comment]
@aicoutos 

Soube hoje, 28-04-2020  que 4 estados colapsaram.  RJ,AM,PE,CE
Hoje,  em obitos, igualamos a China que tem 1 bilhao e 300 milhoes de habitantes.

Em minh opniao, falta:
1- Fazer estatistica sobre os dados, para antecipar as acoes. Estao faltando pessoas de estatistica. Utilizar ferramentas como R, https://www.gnu.org/software/pspp/ alternativa ao  SPSS,...

2- publicar resultados e fazer chegar as pessoas

**Comment by w3gaucho** [comment]
assustador. legal o PSPP, não conhecia, vou testar ele. processar todas essas informações diariamente sozinho pra mim é complicado, por isso prefiro focar apenas na parte da exibição usando os dados disponíveis divulgados pelo MS e replicados aqui pelo @wcota.

seria mais interessante coletar os dados mais recentes diretamente das SES ou dos municípios. minha intenção inicial era mudar as cores dos marcadores dos estados como forma de indicar a situação de cada estado.

meus conhecimentos de estatística são básicos, porém caso seja necessário posso ajudar na parte de web scrapping que conheço bem.

considerando a expectativa de crescimento no número de casos e os dados divulgados sobre o número de leitos disponíveis daria para criar um gráfico com a previsão do colapso dos estados.

o @wcota tem feito o trabalho de acompanhar os dados divulgados pelos [sites de notícias](https://github.com/wcota/covid19br/blob/master/sources.csv), tem muitos dados neles e nos sites das SES que poderiam ser apresentado de uma forma mais simples, leve e direta.

**Comment by yjmenezes** [comment]
@aicoutos 

No caso o DB usa os dados do @wcota, que tem como fonte principal as SESA.
Um baita trabalho, dada a falta de padronizacao das secretarias. Cada uma publica o que quer e como quer. Demoraram a disponibilizar informacoes de *recuperados e falta informacoes de internamento (UTIs e Leitos).
No caso, usando a chave de IBGEID, ligo os dados Covid19 com as tabelas que criei com coordenadas e populacao, retirados do site do IBGE.

Para uma solucao rapida, a custa de menor performance, pode usar o QGIS2WEB. a saida vai prontinha para o Apache. Uma solucao mais sofisticada exigiria Geoserver, ApacheToncat, Mapserver, Javascript, PHP, ...

Tenho procurado pessoas de estatistica. Minha formacao eh cartografia. (  UFV e UFPR )

Vamos somando os esforcos, os conhecimentos.
Se tiver onde divulgar os mapas e resultados, ajudaria muito.

[]s
julio
cartognu.org

**Comment by vitordino** [comment]
show o trabalho @wcota, a cada dia que vejo, mais uma feature ✨ 
(até estava fazendo o `per capita` na mão aqui numa visualização que estou trabalhando) 

acho que para seguir o padrão, poderia ter uma coluna de `new recovered` (não deve dar tanto trabalho como não precisa coletar mais dados)

**Comment by yjmenezes** [comment]
@vitordino 

Eu gerei um DUMP em Postgresql+PostGIS da malha dos municipios (+-5700) com os poligonos e com a populacao.  Se nao usar UNIX, posso gerar CSV ou outro formato QQ, exceto excell. github.com/yjmenezes/

Gerei tambem em Postgresql+Postgis  um  DB com os dados do @wcota.
O dump esta em cartognu.org/mingo/dbsql  com data e qual o commit do @wcota.

Se tiver como divulgar resultados, seria bacana. Os dados que @wcota esta disponibilizando sao valiosos para auxiliar  no enfrentamento ao covid-19.

**Comment by wcota** [comment]
Número de suspeitos e de testes adicionados: https://github.com/wcota/covid19br/commit/078f0f16391ff4562b9a5c88e660bea4789431d3 

Quanto a colunas "newRecovered" e possivelmente suspeitos, vou ver a melhor forma. Não dá trabalho, o problema é a interpretação desses valores já que são dificilmente atualizados em alguns estados.

**Comment by vitordino** [comment]
valeu @yjmenezes, vou dar uma olhada

@wcota realmente faz sentido, a gente acaba dependendo muito da atualização dos dados nas pontas (de estado e município)

**Comment by wcota** [comment]
Vou fechar aqui pois as features já foram adicionadas :)
