### ISSUE TITLE
Novos casos, negativos?

### ISSUE THREAD

**Issue by S0MENTEANDRE** [wcota/covid19br#26]
O número de casos novos do dia 28-03 é negativo em:
https://github.com/wcota/covid19br/blob/master/cases-brazil-states.csv

É normal isto?

**Comment by wcota** [comment]
Olá! Será corrigido em breve :) Os dados estão em fase de migração para usar os do Brasil.IO como fonte, falta apenas ajustar a linha temporal por estado. Para os municípios poderão ter alguns como novos casos negativos, devido à alteração nas informações dos boletins de um dia para o outro. Infelizmente isso acontece.

**Comment by wcota** [comment]
https://github.com/wcota/covid19br/issues/17
