### ISSUE TITLE
Número negativo na coluna "newCases"

### ISSUE THREAD

**Issue by bertolinocastro** [wcota/covid19br#28]
No csv **cases-brazil-cities-time.csv** do commit _67f11168488ba277ae71929651a44d402016a8d0_, a coluna **newCases** está apresentando valores negativos para diversas linhas. Isso é esperado? Obrigado desde já.

**Comment by wcota** [comment]
Olá! Esses números negativos aparecem em pelo menos duas situações. A primeira delas ocorre nas cidades classificadas como "INDEFINIDA/UF". Elas são utilizadas para manter o número de casos do estado naquele dia, mesmo sem ter as localizações definidas. Assim, elas podem aparecer com um número negativo de "novos casos" pois as cidades foram identificadas. Um exemplo muito claro disso é no estado de São Paulo, que costumou ficar 2 ou mais dias sem lançar a relação de cidades.

Já a segunda situação é quando a secretaria de estado erra a localização de um caso. Se ontem divulgaram que haviam 5 casos na cidade A, e hoje dizem que são apenas 1 caso na cidade A, você tem "-4" novos casos. Infelizmente temos de manter assim (via Brasil.IO, veja https://data.brasil.io/dataset/covid19/caso_full.csv.gz) pois não podemos simplesmente deletar essa informação. Sendo assim, mantemos a informação de que a secretaria disse ter 5 casos até ontem na cidade A, enquanto hoje afirmaram ser apenas 1 caso em A.

De qualquer forma, esse tipo de "problema" é resolvido quando as secretarias resolvem divulgar explicitamente a linha temporal dos casos, já com as devidas correções. Isso ainda não aconteceu para todas elas.

**Comment by bertolinocastro** [comment]
Certo. Muito obrigado pela explicação! Levaremos isso em conta nas análises.
