### ISSUE TITLE
Dados desatualizados do Paraná

### ISSUE THREAD

**Issue by gabrielrbarbosa** [wcota/covid19br#29]
Como estão recebendo dados do PR, pelo brasil.io? Vejo apenas dados do dia 22/04
Mas nesse link do governo do PR já tem dados de hoje 25/04 http://www.saude.pr.gov.br/modules/conteudo/conteudo.php?conteudo=3507

**Comment by wcota** [comment]
Sim, são pelo Brasil.IO. Estão atualizados até o dia 23/04, conforme visto na plataforma deles: https://brasil.io/dataset/covid19/caso/?search=&date=&state=PR&city=&place_type=&is_last=&city_ibge_code=&order_for_place=

Não sei dizer o motivo de não terem atualizado ainda para o dia 24/04. Os de hoje ainda devem ser atualizados mais tarde por eles.

**Comment by wcota** [comment]
https://github.com/wcota/covid19br/commit/b45462cb8684ca0fa08b28dfff0034dd1ba149a9

**Comment by wcota** [comment]
Provavelmente relacionado ao problema que aconteceu: 
![image](https://user-images.githubusercontent.com/221582/80391699-6184c680-88ae-11ea-9551-8c9fb0f568b8.png)

http://www.saude.pr.gov.br/arquivos/File/INFORME_EPIDEMIOLOGICO_24_04_2020.pdf
