### ISSUE TITLE
histórico de modalidade por estado

### ISSUE THREAD

**Issue by eduzal** [wcota/covid19br#3]
temos como criar uma coluna de número de mortes na tabela cases-brazil-states.csv?

**Comment by thyagoquintas** [comment]
Como posso te ajudar com isso?
Podemos manter uma base de dados mais atualizada se trabalharmos em conjunto.

**Comment by eduzal** [comment]
oi

imagino apenas que poderiamos ter mais duas colunas nas tabelas cases-brazil-cities-time.csv e cases-brazil-states.csv

não sei se vc tá utilizando um bot para atualização ou se tá atualizando manualmente também.

**Comment by henriquepgomide** [comment]
Olá @wcota ,
Gostaria de saber como poderia ajudar. 
Abraços,
Henrique (UFV)

**Comment by JoseMaranhao** [comment]
Parabéns pela iniciativa!
Concordo que seria muito útil incluir ao menos uma nova coluna em cases-brazil-states.csv, informando o número acumulado de mortes, por estado, ao longo dos dias.

**Comment by wcota** [comment]
Feito! https://github.com/wcota/covid19br/commit/164f8beff24fdb3d6453a8db805d3625f18b23be
