### ISSUE TITLE
verificar estado RJ commit 078f0f1

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#30]
@wcota ,  thx pelo trabalho.

Favor verificar estado RJ commit 078f0f1,  anexo numeros
Os recuperados, existe a possibilidade de ter estes dados por municipio ?

obrigado
julio
[rj2020-04-30.zip](https://github.com/wcota/covid19br/files/4564048/rj2020-04-30.zip)

**Comment by wcota** [comment]
Olá! Obrigado. Foram adicionados no último commit https://github.com/wcota/covid19br/commit/a768326926ba6866c1239ab974fe6351b1a2be79

Quanto aos recuperados por município é praticamente impossível por agora. Se as secretarias passarem a divulgar de maneira estruturada acredito que o Brasil.IO deva compilar esses números e acrescentarei nesse repositório.

**Comment by yjmenezes** [comment]
Valeu

Ok no commit a768326 !
Mais uma vez , obrigado pelo seu trabalho .
