### ISSUE TITLE
Valor inesperado em Santa Catarina

### ISSUE THREAD

**Issue by lf-araujo** [wcota/covid19br#31]
Olá Wesley,

Vc poderia por favor rechecar este valor negativo em SC nos casos novos para a última data:

![image](https://user-images.githubusercontent.com/10139950/80860236-c9d00100-8c3c-11ea-8bae-2028c975df83.png)

![image](https://user-images.githubusercontent.com/10139950/80860254-e0765800-8c3c-11ea-9e11-e78d44ae2a94.png)

É esperado?

**Comment by wcota** [comment]
Olá! Foi erro da secretaria de saúde:

"A Secretaria de Estado da Saúde explica que a redução no número em relação ao divulgado no dia anterior se deve à correção de casos que estavam registrados em duplicidade, fato ocorrido quando o painel do Governo do Estado integrou dados de outros sistemas do Ministério da Saúde, como o Sistema de Laboratório, o e-SUS VE e SIVEP Gripe. O órgão está trabalhando para evitar novos registros em duplicidade nos boletins futuros, e também pediu aos notificadores dos sistemas para que tenham atenção no preenchimento das informações."

http://sc.gov.br/noticias/temas/coronavirus/coronavirus-em-sc-governo-do-estado-confirma-2-104-casos-e-50-obitos-por-covid-19

https://github.com/wcota/covid19br/commit/4c8c99b14324302563509a6c2aef9b9eb879dd36

**Comment by wcota** [comment]
https://github.com/wcota/covid19br/commit/8a2c1c20851c05f1db34bfb766770e18ab65d0a6
