### ISSUE TITLE
Novos casos negativos

### ISSUE THREAD

**Issue by S0MENTEANDRE** [wcota/covid19br#33]
2020-05-01 | Brazil | SC | TOTAL | 2 | 50 | -290

**Comment by S0MENTEANDRE** [comment]
linha 1411

**Comment by S0MENTEANDRE** [comment]
https://github.com/wcota/covid19br/blob/master/cases-brazil-states.csv

**Comment by wcota** [comment]
https://github.com/wcota/covid19br/issues/31 

Olá! Foi erro da secretaria de saúde:

"A Secretaria de Estado da Saúde explica que a redução no número em relação ao divulgado no dia anterior se deve à correção de casos que estavam registrados em duplicidade, fato ocorrido quando o painel do Governo do Estado integrou dados de outros sistemas do Ministério da Saúde, como o Sistema de Laboratório, o e-SUS VE e SIVEP Gripe. O órgão está trabalhando para evitar novos registros em duplicidade nos boletins futuros, e também pediu aos notificadores dos sistemas para que tenham atenção no preenchimento das informações."

http://sc.gov.br/noticias/temas/coronavirus/coronavirus-em-sc-governo-do-estado-confirma-2-104-casos-e-50-obitos-por-covid-19

https://github.com/wcota/covid19br/commit/4c8c99b14324302563509a6c2aef9b9eb879dd36

**Comment by S0MENTEANDRE** [comment]
OK

**Comment by wcota** [comment]
https://github.com/wcota/covid19br/commit/8a2c1c20851c05f1db34bfb766770e18ab65d0a6
