### ISSUE TITLE
Inconsistência dados estado RN | boletins com dados do dia anterior

### ISSUE THREAD

**Issue by alemaiorano** [wcota/covid19br#35]
Oi Wesley! Primeiramente parabéns pelo trabalho. Estou com uma dúvida sobre os dados do RN. Me parece que estão shiftados. Note que o valor mais recente está como 0 e que as demais estão com um lag 1. No geral difere da fonte. Abs obrigado

**Comment by wcota** [comment]
Olá! Obrigado E de fato, parecem estar deslocados. Estou em contato com o Brasil.IO para ver o que aconteceu. Em breve será corrigido :)

**Comment by wcota** [comment]
Olá! Desculpa a demora em responder. A informação que tive é de que alguns estados passaram a divulgar nos boletins os dados referentes ao dia anterior, que foi o caso do RN.
