### ISSUE TITLE
Existe um problema com os dados do cases-brazil-cities.csv

### ISSUE THREAD

**Issue by andre-fs-ferreira** [wcota/covid19br#36]
Algumas cidades não estão com informação como por exemplo São Desidério e Correntina.
Não sei se não existem mesmo dados ou foi apenas lapso.

**Comment by wcota** [comment]
Olá!
O problema seria não ter casos confirmados nessas duas cidades ainda? Sabe se a secretaria estadual já confirmou esses casos, e em qual dia?

**Comment by andre-fs-ferreira** [comment]
Sim, afinal o dataset está completo, essas informações é que não existem. https://covid.saude.gov.br/
Nos mapas dá para notar esses casos, está bastante idêntico ao que tentei construir, pensava que poderia ter eu algum erro. 
Obrigado pela atenção e continuação de bom trabalho!
