### ISSUE TITLE
New cases by city

### ISSUE THREAD

**Issue by henriquepgomide** [wcota/covid19br#4]
Hi there!
First. Congrats on your great work!
Second. Are you tracking of all Brazilian cities? If so, how reliable are your sources?.
Regards,

**Comment by wcota** [comment]
Olá!
Obrigado! :)
As informações dos municípios são obtidas a partir dos boletins disponibilizados pelas secretarias de saúde e informações da mídia (geralmente eles conseguem pelas coletivas de imprensa, etc). As fontes estão aqui: https://github.com/wcota/covid19br/blob/master/sources.csv
