### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by ghost** [wcota/covid19br#40]
Meu nobre, boa noite!
Você teria acesso e/ou como disponibilizar os dados de casos descartados por município? A ideia é poder calcular o número de testes realizados somando os valores de descartados+confirmados.
Abraços!

**Comment by yjmenezes** [comment]
Aproveitando,  algumas capitais passaram a fornecer dados por bairro ou regionais de saude do municipio.  DF, BH, Curitiba.  Existe a dificuldade de, infelizmente, nao haver um padrao e publicarem em formatos PDF ou XLSX, em todo caso, seria interessante dar uma olhada. 

@jivag0  carreguei os dados do @wcota (muitissimo obrigado) em formato Postgresql+PostGIS, tendo acrescido a populacao e area de cada municipio e as geometrias em forma de ponto, linha e poligono. Se te interessar, pode baixar de cartognu.org
