### ISSUE TITLE
Inconsistência há dois dias em município

### ISSUE THREAD

**Issue by ghost** [wcota/covid19br#41]
Boa noite!

Ontem e hoje observei discrepâncias nos dados de casos do município de Sousa-PB
O valor do dia 16 está negativo e a variação dos ultimos dias está diferente do boletim oficial

**Comment by wcota** [comment]
Olá! Quanto ao caso de Sousa-PB, é isso mesmo. No dia 15/05 relataram 63 casos: https://paraiba.pb.gov.br/diretas/saude/coronavirus/noticias/atualizacao-covid-19-15-05

Já no dia 16/05, relataram 62 casos: https://paraiba.pb.gov.br/diretas/saude/coronavirus/noticias/atualizacao-covid-19-16-05

Por isso o "newCases" fica negativo. Conferi também outros dias como 19/05 e 20/05, e consta o mesmo valor que em `cases-brazil-cities-time.csv`

**Comment by ghost** [comment]
então deve ter algum erro no levantamento do Estado. Os boletins do município mostram outros números. Vou investigar mais pra ver o que houve. Obrigado!!

edit: https://www.instagram.com/p/CAOQtwgF1qe/?utm_source=ig_web_copy_link

**Comment by wcota** [comment]
Entendi! Os boletins por município são diferentes sim dos dados aqui, pois apenas consolidamos os dados relatados pelos estados. Existe atraso na contabilização pelas secretarias estaduais dos casos de cada município, por isso a diferença :)
