### ISSUE TITLE
faltando Total de testes de AM e RJ

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#42]
cases-brazil-total.csv  commit  57af3ce,   

@wcota , estao zerados os testes de RJ e AM.  

obrigado pelo seu trabalho.

julio
cartognu.org  2020-05-20

**Comment by wcota** [comment]
Olá! É porque não temos esses dados mesmo :) 
https://docs.google.com/spreadsheets/d/1MWQE3s4ef6dxJosyqvsFaV4fDyElxnBUB6gMGvs3rEc/edit?usp=sharing

**Comment by yjmenezes** [comment]
@wcota , eu imaginei, que poderiam nao estar disponibilizando.

valeu.
[]s
julio
http://cartognu.org/mingo/brasil/resumo_brasil.html
