### ISSUE TITLE
negative values for newCases and newDeaths in cases-brazil-cities-time.csv

### ISSUE THREAD

**Issue by marcuswac** [wcota/covid19br#43]
There are 1670 negative entries for `newCases` and 165 negative entries for `newDeaths` in `cases-brazil-cities-time.csv` file. I noticed that because I'm using the `EpiForecasts` packages and noticed negative cases in "Santa Catarina" cases plots in their posts: https://epiforecasts.io/covid/posts/national/brazil/

They are using your data to generate the Brazilian analysis.

How to reproduce:

```
library(dplyr)
read.csv("https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv") %>%
    filter(newCases < 0)
```      

Output (first 5 lines):
```
 date country state                             city  ibgeID newDeaths deaths newCases totalCases
1  2020-03-12  Brazil    RJ CASO SEM LOCALIZAÇÃO DEFINIDA/RJ      33         0      0       -9          1
2  2020-03-18  Brazil    PE       Jaboatão dos Guararapes/PE 2607901         0      0       -1          1
3  2020-03-19  Brazil    SP                   Santo André/SP 3547809         0      0       -4          2
4  2020-03-19  Brazil    SP            São Caetano do Sul/SP 3548807         0      0       -5          1
5  2020-03-20  Brazil    MG                    Uberlândia/MG 3170206         0      0       -1          1
...
```

**Comment by wcota** [comment]
Olá! Esses casos negativos aparecem devido à correção nos boletins das secretarias de saúde, quando corrigem a localização de cada caso, ou um caso é, digamos, "desconfirmado" (testes refeitos, erro de informação, etc). Isso acontece com certa frequência, como pode ser visto nessa sua análise. Os casos aqui descritos são tais como reportados pelos boletins das secretarias. Já em "CASO SEM LOCALIZAÇÃO DEFINIDA/UF" praticamente sempre aparecem newCases < 0 pois no boletim seguinte identificaram a localização desses casos.

Quanto ao de Santa Catarina, a explicação está aqui: https://github.com/wcota/covid19br/issues/31 e documentado nesse arquivo: https://github.com/wcota/covid19br/blob/master/_fixes_meta.csv

De qualquer forma vou deixar essas informações mais explícitas na próxima versão da documentação disponível em https://preprints.scielo.org/index.php/scielo/preprint/view/362/version/371

Obrigado!

**Comment by marcuswac** [comment]
obrigado pela informação. minha preocupação maior é que estão usando os dados como estão para fazer projeções, como o https://epiforecasts.io/covid/posts/national/brazil/

seria interessante entrar com contato com eles para corrigirem essas inconsistências nos dados geradas por inconsistências dos boletins. mas entendo que o problema é na divulgação dos dados nos boletins das secretarias de saúde

**Comment by jivag0** [comment]
Meu caro, aproveitando o ensejo do colega: sobre a última questão de erros nos numeros da PB: verifiquei que houve algum descompasso na comunicação da sec. mun. para a sec. est. Por isso aconteceram as inconsistências. No entanto já foram corrigidas. Reparei apenas que em duas datas ainda constam casos sem local definido na Paraíba. Quando somo esses novos casos, passa da contagem oficial da secretaria. O que poderia estar acontecendo? A secretaria de Estado divulgou esses casos SLD e não corrigiu depois? Ou os excluiu? Abraços. Atte, Jivago

PS.: estou usando seu banco para processar dados estaduais e municipais, por isso a importância de um caso a mais ou a menos, entende? Como comecei o estudo com seu banco, acho honesto ir até o fim para referenciar seu trabalho. =)
