### ISSUE TITLE
sugestao:  numeros de isolamento social

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#44]
@wcota 

Sei das enormes dificuldades em compilar os dados, mas creio que isolamento social e testes sao dados importantes para analises.  Poderiam colocar na fila de desejos ! 

obrigado e
[]s
julio

**Comment by wcota** [comment]
Olá!

De fato seria muito interessante mas 1) como esses dados são de propriedade de uma empresa e 2) não tenho tempo suficiente para fazer isso, prefiro que encontre/entre em contato diretamente na página que há esses dados por municípios: https://www.ime.usp.br/~pedrosp/covid19/#iso_index

**Comment by yjmenezes** [comment]
@wcota 

obrigado pelo retorno,  vou acessar a pagina do prof. Pedro da Silva Peixoto.

[]s
julio
cartognu.org/covid19
