### ISSUE TITLE
valores de newDeaths em 26 e 27 maio

### ISSUE THREAD

**Issue by eduzal** [wcota/covid19br#45]
olá

depois do update de cidades do MS os números de newDeaths deram uma pirada. 
26/5 tinham 1056 pulou para 1590
e
27/5 que já tava com mais de mil caiu para 520

**Comment by eduzal** [comment]
apareceu um pico em Roraima nesses dois dias que deixaram os valores meio malucos

**Comment by wcota** [comment]
Olá! 
Conferi aqui e o que aconteceu é que o Ministério da Saúde atualizou o número de óbitos dos municípios de Roraima para o dia 26/05. No arquivo do dia 26 de maio, Boa Vista tinha 83 óbitos confirmados. Já no dia 27 de maio, afirmam que no dia 26/05 foram 611 óbitos.

Ou foi erro de introdução de dados por eles, ou estão fazendo a correção por data de óbito, e não de notificação. Essa informação será sobrescrita quando o Brasil.IO lançar os boletins de RR

[HIST_PAINEL_ COVIDBR_26mai2020.xlsx](https://github.com/wcota/covid19br/files/4692711/HIST_PAINEL_.COVIDBR_26mai2020.xlsx)

[HIST_PAINEL_COVIDBR_27mai2020.xlsx](https://github.com/wcota/covid19br/files/4692707/HIST_PAINEL_COVIDBR_27mai2020.xlsx)

**Comment by wcota** [comment]
O pior que tá completamente esquisito mesmo. A soma não bate na planilha, e para a data de hoje falam em menos óbitos nessas cidades...

**Comment by wcota** [comment]
![image](https://user-images.githubusercontent.com/221582/83088571-61860b00-a094-11ea-8c86-614de36a30e4.png)

**Comment by wcota** [comment]
Como os dados estavam inconsistentes, apliquei um fix para remediar isso enquanto os boletins do Brasil.IO não saem.

**Comment by eduzal** [comment]
show!

**Comment by wcota** [comment]
Muito obrigado por ter avisado sobre isso! Vou fechar a issue aqui :)

**Comment by wcota** [comment]
Agora o problema tá afetando todos os estados: https://twitter.com/wlcota/status/1266863591032074242

https://twitter.com/tiagotvv/status/1266873830527709184
