### ISSUE TITLE
CE commit 6d14264 , novos casos 9047

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#46]
@wcota 

Sera que tem algum engano no CE ?
Novos casos:  9427

obrigado,
julio
cartognu.org/covid19

**Comment by wcota** [comment]
Está correto. https://g1.globo.com/ce/ceara/noticia/2020/05/30/ceara-ultrapassa-100-mil-testes-para-covid-19-realizados-e-estado-passar-a-registrar-mais-76-mil-casos.ghtml

Logo depois teve mais uma atualização na plataforma oficial.

**Comment by yjmenezes** [comment]
@wcota 

Bom dia !

Obrigado pelo retorno!

Eu imaginei que o salto do CE  poderia ser fruto de falta de testes ou atrasos de notificacoes de dias anteriores.  
O RJ ainda nao publicou a quantidade de testes, deve ocorrer o mesmo fenomeno no RJ.
Vou atualizar o grafico de testes hoje.

Com esse  28885 obitos, seria como dizimar municipios inteiros.  Selecionei 46 municipios nesta faixa de populacao. 

SP-capital ja deve encostar em Wuhan em casos e obitos em breve.

[]s
julio
cartognu.org/covid19
