### ISSUE TITLE
commit 2826326 dados de  TO,MS,RN  com zero

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#49]
@wcota 

No commit 2826326, os dados de  TO,MS,RN  estao com zero.
Teria como confirmar ?

obrigado,
julio
cartognu.org/covid19

**Comment by wcota** [comment]
Bem observado! Darei uma olhada. Acredito que tenha sido por conta da mudança na contagem dos estados pelo Brasil.IO

**Comment by yjmenezes** [comment]
@wcota 

obrigado por sua dedicacao, em pleno domingo.

cases-brazil-total.csv  commit 6b7bdef,  continuam zero  TO,MS,RN.

[]s
julio
cartognu.org/covid19

**Comment by wcota** [comment]
Esses estados estão divulgando os casos do dia anterior e podem ter esse problema de "novos casos" iguais a 0, pois só saberemos no dia seguinte. O RN, por exemplo, divulga hoje o número de casos registrados até ontem! 
É lamentável essa falta de padrão entre secretarias, mas é a vida. De qualquer forma esses números vão sendo atualizados nos arquivos históricos com o passar do tempo.

**Comment by yjmenezes** [comment]
@wcota 

obrigado novamente,  desculpe-me, era para eu ter fechado o topico.

Vamos em frente, fazendo nossa parte e tentando divulgar a situacao da melhor e mais honesta forma possivel
