### ISSUE TITLE
Inconsistência entre os dias 7 e 8 de junho na PB

### ISSUE THREAD

**Issue by ghost** [wcota/covid19br#51]
**fechei por que pensei ter resolvido

Pode dar uma olhada nisso em algum momento, por favor?

**Comment by wcota** [comment]
Olá! Estou vendo isso! :) Algum erro ocorreu na contagem do número total de casos por estado no Brasil.IO e os casos do dia 8 foram adicionados nos registros do dia 7. Assim que tiver uma correção atualizarei os dados aqui.

**Comment by wcota** [comment]
Corrigido!
