### ISSUE TITLE
dia 8 de junho sem dados de Alagoas

### ISSUE THREAD

**Issue by travitzki** [wcota/covid19br#52]
Opa, vi que Alagoas está zerado em novos casos e mortes no dia 8 de junho. 
Mas o informe epidemiológico do dia não confirma isso.
Só pra avisar, muito obrigado pelo trabalho!

**Comment by wcota** [comment]
Obrigado! Parece estar relacionado ao mesmo problema na Paraíba: https://github.com/wcota/covid19br/issues/51

Estou aguardando a equipe do Brasil.IO corrigir esse possível erro pois a origem da inconsistência é de lá :) Aparentemente colocaram os casos do dia 8 no dia 7, ficando "0 novos casos" no dia 8

**Comment by wcota** [comment]
A questão é mais complicada que eu imaginava :)

O Brasil.IO está utilizando os dados dos boletins lançados por Alagoas. No boletim do dia 7, disseram que os números eram do dia 6: http://www.saude.al.gov.br/wp-content/uploads/2020/06/Informe-Epidemiol%C3%B3gico-COVID-19-n%C2%BA-93-7-6-2020.pdf
Aparece nos rodapés "Fonte: CIEVS/AL dados em 6/06/2020."

Já no do dia 8, aparece referente ao dia 7: http://www.saude.al.gov.br/wp-content/uploads/2020/06/Informe-Epidemiol%C3%B3gico-COVID-19-n%C2%BA-94-8-6-2020.pdf, rodapé "Fonte: CIEVS/AL dados em 7/06/2020"

Até aí, tudo bem. Eis que no dia 9 (http://www.saude.al.gov.br/wp-content/uploads/2020/06/Informe-Epidemiol%C3%B3gico-COVID-19-n%C2%BA-95-9-6-2020.pdf) passaram a colocar os dados do próprio dia, rodapé "Fonte: CIEVS/AL dados em 9/06/2020."

Para os dados serem fieis aos relatados pela secretaria, ficou desse jeito. Por isso o dia 8 ficou sem novos casos.
