### ISSUE TITLE
Caso sem localização (persistente) e inconsistência em 14-15/06

### ISSUE THREAD

**Issue by ghost** [wcota/covid19br#56]
Meu caro, bom dia!
Eu penso e repenso muitas vezes antes de abrir um issue, pois nem imagino o trabalho que vocês estão tendo! Peço licença para dividir mais uma questão:

1- Na Paraíba, existe 1 caso no dia 08/05 e uma morte no dia 30/05 que constam como "Sem Localização Definida". Eles, no final, somam como um excedente ao número real divulgado pela SES. Foi um erro da secretaria ou há alguma especificidade sobre esses dias? Há algum tempo eu venho apagando eles esperando ser corrigido naturalmente, mas ainda persistem e resolvi compartilhar.

2- Outra questão é que, aparentemente (pensando muito aqui, rs), acredito que os dados individualizados do dia 14/06 estão somados aos do dia 15/06 (a compensação dos casos SLD no dia 14 está registrada no dia 15)

Como eu trabalho com os dados, tanto por município quanto por semana epidemiológica, esses detalhes de individualizações ficam contrastados pra mim; por isso essas questões tão específicas! Obrigado pela sua dedicação!

Um abraço!

**Comment by wcota** [comment]
Esses problemas foram corrigidos? Na Paraíba de fato haviam alguns problemas que foram corrigidos depois pelo Brasil.IO.

Caso persistam, confira se o problema existe em https://brasil.io/dataset/covid19/caso_full/

Se sim, entre em contato com https://chat.brasil.io/ informando do possível problema.

Quanto aos casos sem localização de um dia podem ser "localizados" apenas no outro dia. Os dados são por data de divulgação e não necessariamente a linha do tempo passada é corrigida.

Abraço!
