### ISSUE TITLE
commit 37c34f8,  Curitiba, faltando novos casos e obitos.

### ISSUE THREAD

**Issue by yjmenezes** [wcota/covid19br#58]
@wcota,

Bom dia !

Algumas capitais, faltam dados em  cases-brasil-cities-time.csv

commit 37c34f8, 
Curitiba, faltando novos casos e novos obitos, nos  3 dias finais do arquivo.

Recife, tem um probleminha de valor negativo em novos casos em 2020-04-24
17,2020-04-24,Brazil,PE,Recife/PE,2611606,26010,Recife,14,152,-415,1647,9.23604,100.07735,0.09229,SES,2020-07-24
Sei que podem ocorrer, em todo caso, so para constar.

obrigado,

julio
cartognu.org/covid19

**Comment by yjmenezes** [comment]
@wcota e @dsevero 

Verifiquei aqui e houve alteracao no Site da Secretaria do Estado do PR, a partir do dia 25/Julho ate o dia29/Julho, nao geraram o Casos_e_Obitos.csv.  Tem um Geral.csv que creio possa ser filtrado.

http://www.saude.pr.gov.br/Pagina/Coronavirus-COVID-19
Se puderam dar uma olhada, 

[]s
julio
cartognu.org/covid19

**Comment by wcota** [comment]
Obrigado! Como os casos por município pego exclusivamente pelo Brasil.IO, aguardo que eles leiam esses boletins para atualizar os dados.

As últimas datas de boletins são: 

```
{'SP': '2020-07-30',
 'RJ': '2020-07-30',
 'BA': '2020-07-30',
 'DF': '2020-07-29',
 'AL': '2020-07-30',
 'MG': '2020-07-30',
 'RS': '2020-07-30',
 'GO': '2020-07-30',
 'PE': '2020-07-29',
 'PR': '2020-07-24',
 'RN': '2020-07-28',
 'SC': '2020-07-30',
 'AM': '2020-07-30',
 'MS': '2020-07-29',
 'SE': '2020-07-29',
 'CE': '2020-07-30',
 'AC': '2020-07-29',
 'PA': '2020-07-30',
 'PB': '2020-07-30',
 'TO': '2020-07-29',
 'ES': '2020-07-30',
 'PI': '2020-07-30',
 'AP': '2020-07-30',
 'MA': '2020-07-30',
 'MT': '2020-07-23',
 'RO': '2020-07-29',
 'RR': '2020-07-29'}
```

Caso eles demorem muito para atualizar, basta entrar em contato em https://chat.brasil.io/
Quanto ao do MT me informaram que a secretaria passou a colocar os dados em imagem dentro do PDF e isso dificultou bastante o trabalho de atualização dos dados.

Em relação aos novos casos e óbitos negativos não há muito o que fazer. Os dados são por data de divulgação, não de notificação ou sintomas, por exemplo. Isso só será possível de ser corrigido num futuro, quando disponibilizarem todos os dados da maneira detalhada, com atualização da linha do tempo.

**Comment by yjmenezes** [comment]
@wcota 

infelizmente falta uma coordenacao a nivel nacional para definir, no minimo, um padrao para a divulgacao dos dados.
Vamos em frente,  informacao eh fundamental para o enfrentamento do covid-19;

Parece-me que estamos naturalizando a catastrofe no Brasil !

[]s
julio
cartognu.org/covid19
