### ISSUE TITLE
Commit 6936053 faltando dado de vários estados

### ISSUE THREAD

**Issue by GabrielGGuerreiro** [wcota/covid19br#59]
Estados do RN, SP, TO, MS com 0 novos casos no dia 28/07/2020, está correto?

**Comment by wcota** [comment]
Os dados municipais são alimentados via Brasil.IO, e os dados estaduais são computados a partir deles + Ministério da Saúde.
Do RN o Brasil.IO notificou o mesmo número de casos do dia 27/07 no dia 28/07.
SP não divulgou casos ontem: https://twitter.com/anarina/status/1288277528734564355
Pode ter acontecido também para outros estados.

**Comment by wcota** [comment]
As últimas datas de atualização foram:

```
{'SP': '2020-07-30',
 'RJ': '2020-07-30',
 'BA': '2020-07-30',
 'DF': '2020-07-29',
 'AL': '2020-07-30',
 'MG': '2020-07-30',
 'RS': '2020-07-30',
 'GO': '2020-07-30',
 'PE': '2020-07-29',
 'PR': '2020-07-24',
 'RN': '2020-07-28',
 'SC': '2020-07-30',
 'AM': '2020-07-30',
 'MS': '2020-07-29',
 'SE': '2020-07-29',
 'CE': '2020-07-30',
 'AC': '2020-07-29',
 'PA': '2020-07-30',
 'PB': '2020-07-30',
 'TO': '2020-07-29',
 'ES': '2020-07-30',
 'PI': '2020-07-30',
 'AP': '2020-07-30',
 'MA': '2020-07-30',
 'MT': '2020-07-23',
 'RO': '2020-07-29',
 'RR': '2020-07-29'}
```

Caso esse problema persista, favor conferir o dataset fonte por município https://brasil.io/dataset/covid19/caso_full/ e entrar em contato com https://chat.brasil.io/
Lembrando que SP sim ficará sem novos casos pela falta de divulgação naquele dia.

**Comment by wcota** [comment]
A coluna `_source` indica de onde saíram os dados para cada município. Aquelas datas com `_source = SES` vieram do Brasil.IO, enquanto as com `_source = MS` são do Arquivo CSV do Ministério da Saúde https://covid.saude.gov.br/

Atualmente todos os estados são preenchidos com os dados desse arquivo do MS após a última data de coleta do Brasil.IO para tentar contornar esse problema de atualização de dados. Mas como no issue #63, não dá pra confiar no MS e problemas vão acontecer.
