### ISSUE TITLE
Casos Ativos

### ISSUE THREAD

**Issue by gustavoarcanjo** [wcota/covid19br#60]
Sugestão de apresentar, no site, os casos ativos (que imagino que podem ser calculados com base nos dados de casos recuperados, mortes e casos totais).

Alguns sites como o worldometers calculam da seguinte forma:

> _Active Cases = (total cases) - (total deaths) - (recovered). This figure represents the current number of people detected and confirmed to be infected with the virus. This figure can increase or decrease, and represents an important metric for Public Health and Emergency response authorities when assessing hospitalization needs versus capacity._

Entretanto, não encontrei algum site que apresente essa informação por região ou município, no Brasil.

**Comment by wcota** [comment]
Como apenas temos os números de recuperados por estado, não é possível fazer esse cálculo por município. 
De qualquer forma a página em portuguẽs apresenta esses dados nos menus por estado e evolução temporal em "Gráficos por região, estado ou município" https://covid19br.wcota.me/#graficos

Que fique claro que não necessariamente um "recuperado" pela secretaria de saúde significa que o caso está inativo. Algumas consideram como recuperado aqueles que ou não faleceram ou não estão internados.

**Comment by gustavoarcanjo** [comment]
Muito obrigado pelas informações :)
