### ISSUE TITLE
Recoveries Doubling in State Data

### ISSUE THREAD

**Issue by akatz2** [wcota/covid19br#61]
Good evening @wcota . It looks like the recoveries are somehow doubling from the state data right now (Aug 15 01:51 GMT).  For example, Alagoas is reporting 65k recoveries but https://github.com/wcota/covid19br/blob/master/cases-brazil-total.csv lists 130k.  Similarly, Minas Gerais is reporting 135,981 but the file has 271,962 (exactly double).  This seems to hold for all the recoveries in the file this evening.  Thanks again for your work!

**Comment by wcota** [comment]
Thanks! :D
