### ISSUE TITLE
Arquivo cases-brazil-cities-time.csv não foi atualizado e cases-brazil-cities-time.csv.gz foi

### ISSUE THREAD

**Issue by GabrielGGuerreiro** [wcota/covid19br#62]
troquei minha rotina para baixar o gz e unzipar ele, mas só para deixar registrado o csv não foi atualizado em 2 dias

**Comment by wcota** [comment]
Bom dia! O arquivo .csv não será mais atualizado por conta do limite de 100 MB do Github. Mantive o arquivo original por questão de compatibilidade.

https://github.com/wcota/covid19br/blob/master/UPDATES.md

Esqueci de colocar o comentário sobre não atualizar mais o .csv, adicionei lá.
