### ISSUE TITLE
07/11 e 08/11 com vários valores de novos casos negativos

### ISSUE THREAD

**Issue by GabrielGGuerreiro** [wcota/covid19br#63]
O que houve nesses dias que causou essa distorção? 
O Arquivo que peguei esses dados é o:
cases-brazil-cities-time.csv.gz
Por exemplo Berford Roxo/RJ:
 - 06/11 (0 casos novos e 11206 casos totais)
 - 07/11 (11120 casos novos e 22326 casos totais)
 - 08/11 (-11179 casos novos e 11147 casos totais)

Existem outros casos, só postei essa dúvida mesmo

**Comment by wcota** [comment]
Os dados entre os dias 5 até 11 ou 12 serão bem confusos por conta do apagão no SIVEP do Ministério da Saúde. No caso, esses números do RJ vem da planilha divulgada pelo próprio em https://covid.saude.gov.br/ (source = MS desde o dia 29/10/2020). Se os dados de hoje não corrigirem isso, terei de ver o que fazer. 

Muito provavelmente é um erro grotesco do Ministério da Saúde acumulando dados. Já aconteceu no passado. Tá difícil
