### ISSUE TITLE
Mudança de dados entre datas

### ISSUE THREAD

**Issue by eduardopaula** [wcota/covid19br#65]
Boa tarde, 

venho acompanhando o site e vi que em algumas cidades os dados de óbitos mudou, no caso sigo a cidade de Uberlândia/MG

 . Anexo as imagens do bug:
 Uberlândia - óbitos na data do dia 10/03/2021
 ![UDI DIA 10-03-21](https://user-images.githubusercontent.com/11997192/111187190-8a7b7c00-8592-11eb-817b-1ad222fb2090.jpeg)
 Uberlândia - óbitos na data do dia 15/03/2021
![2kvqs0on](https://user-images.githubusercontent.com/11997192/111187298-a3842d00-8592-11eb-9d97-adca5393dcdd.png)

**Comment by wcota** [comment]
Boa tarde!

Obrigado pelo aviso. 
Verifiquei aqui e o problema vem do Brasil.IO. Os novos casos e óbitos entre 19/02/2020 e 11/03/2020 aparecem zerados na base deles e refletiu nesse aumento drástico.

![image](https://user-images.githubusercontent.com/221582/111189737-af81e600-85b6-11eb-9047-837f5dfb7f97.png)

Assim que possível vou corrigir esses dados.

**Comment by wcota** [comment]
Corrigido!
