### ISSUE TITLE
Série temporal de vacinação

### ISSUE THREAD

**Issue by vitorwilher** [wcota/covid19br#68]
Olá, Wesley, tudo bem?

Muito bom o repositório. Não encontrei, entretanto, a série temporal de vacinação por estados.

Ela existe? 

No arquivo "cases-brazil-states.csv" a coluna "vaccinated" está com NA para todo o horizonte.

Desde já agradeço. 

Abs

**Comment by wcota** [comment]
Olá! Tudo bem, e você?

Os dados estão sendo atualizados sim. Veja exemplos para a vacinação no final do notebook em: https://colab.research.google.com/drive/1H1N387IIAGV-3YRtyxzPz94vSiLrhE0M?usp=sharing

São as colunas `vaccinated` (primeira dose) e `vaccinated_second` (segunda dose) desses arquivos dos estados.

Se não conseguir, só me avisar novamente. Mas por aqui está tudo certo!

Abraço,
Wesley

**Comment by vitorwilher** [comment]
Obrigado pela resposta, Wesley.

Consegui aqui. 

Abs
