### ISSUE TITLE
Recuperados por 100 mil habitantes

### ISSUE THREAD

**Issue by geekley** [wcota/covid19br#69]
A maioria dos gráficos em https://covid19br.wcota.me/#graficos que compara municípios, estados ou regiões tem muito mais significado se for relativo ao número de habitantes. Se não, é óbvio que SP vai ficar na frente em qualquer tipo de estatística comparando estados, por exemplo.

1. Nem todas as opções do dropdown têm "por 100 mil habitantes". Recuperados, por exemplo, só tem absoluto, ao que parece; precisa ter também "Recuperados por 100 mil habitantes" para poder comparar essa variável direito entre os locais.
2. Na comparação de estados, eu penso que seria melhor ter, por exemplo, "casos por 100 mil habitantes" como a opção padrão selecionada em vez de "casos totais". Eu ainda iria além e ordenaria o dropdown de modo a botar todas as estatísticas relativas junto, e antes das absolutas, já que elas têm maior significado em termos de comparação entre locais.

**Comment by wcota** [comment]
Obrigado pela sugestão! A página atual não passará por atualizações por estar de bem difícil manutenção, já que todo o código foi construído às pressas e "ao vivo". Iniciei no ano passado a construção de uma nova, mas não sei dizer se terei tempo de terminá-la. Portanto, fica assim por enquanto :)
