### ISSUE TITLE
Dados do MS-SUS

### ISSUE THREAD

**Issue by drykxs** [wcota/covid19br#70]
Sugiro levar em consideração os dados do Ministério da Saude. De onde você está buscando tem uma demora grande na atualização. Por exemplo hoje (14/04/2021) que ninguém foi vacinado no DF. Mas foi. Pouco, mas foi. Os dados do MS-SUS são atualizados com maior frequência .

https://viz.saude.gov.br/extensions/DEMAS_C19Vacina/DEMAS_C19Vacina.html

**Comment by drykxs** [comment]
https://viz.saude.gov.br/extensions/DEMAS_C19Vacina/DEMAS_C19Vacina.html

**Comment by wcota** [comment]
Obrigado pelo comentário. No caso, a nossa base tem mais doses aplicadas do que o ministério, por isso não aparecem essas doses aplicadas hoje. Os atrasos nos números do ministério são grandes. A fonte que uso pega os números mais atualizados direto das secretarias estaduais ou do Distrito Federal.
Por um lado temos um número mais fiel à realidade quanto ao número de doses aplicadas até aquele dia, mas por outro lado não temos exatamente quantas doses foram efetivamente aplicadas naquele dia. Os dados aqui são por data de divulgação dos números, não ocorrência, assim como ocorre com casos e óbitos.

Vale lembrar que os números do ministério são calculados diretamente dos microdados e por isso são retroativamente atualizados. Há um atraso bem considerável para esses dados chegarem até eles.

**Comment by drykxs** [comment]
Obrigada. Vi que realmente sua página está atualizando mais rapido e essa do MS até não existe mais. 

;)
