### ISSUE TITLE
Atualização dos dados

### ISSUE THREAD

**Issue by marmello77** [wcota/covid19br#75]
Olá, Wesley!

Primeiramente, parabéns pelo excelente trabalho feito neste repo. Ele tem sido uma das fontes em que mais confio e que mais recomendo desde o começo da pandemia.

Vi a sua entrevista sobre o apagão de dados do governo federal. O quanto esse problema está afetando os dados usados aqui neste repo? Por exemplo, acompanhando as curvas de São Paulo capital, temos a impressão de que a pandemia foi controlada desde dezembro. Mas, como vocês comentaram na entrevista, cada vez mais ouvimos relatos de parentes, amigos, colegas e conhecidos testando positivo, inclusive para ômicron.

Qual é a real situação no momento? Você está conseguindo atualizar o repo da maneira como gostaria apenas com os dados das secretarias de saúde?

Muito obrigado pelo serviço de utilidade pública!

Um abraço,

Marco

**Comment by wcota** [comment]
Olá!

Só hoje estava lendo a lista de issues e vi sua pergunta. Os dados aqui continuaram sendo atualizados naquela época, com a diferença que a fonte vinda diretamente do Ministério da Saúde não funcionava mais (muitos dados por municípios vem do CSV que o ministério disponibiliza). Porém, as secretarias estaduais já tinham uma contagem independente, inclusive junto ao CONASS, que permitiu incorporar essas informações retroativamente. Em termos práticos não afetou muito, mas certamente pode ter afetado no índice de subnotificação por conta da dificuldade dos municípios e estados a informarem os dados nos sistemas internos do SUS.

Abraço!
Wesley
