### ISSUE TITLE
Arquivo "cases-brazil-cities-time.csv.gz" perdeu observações

### ISSUE THREAD

**Issue by cassianord** [wcota/covid19br#76]
O arquivo dos municípios segundo data, "cases-brazil-cities-time.csv.gz", tinha mais de 4 milhões de observações, mas agora está com menos de 700 mil observações. Pelo que percebi, ele está sem os dados anteriores a 2022.

**Comment by cassianord** [comment]
Ignorar, acabei de observar que foram segregados os dados anteriores em arquivos diferentes.

**Comment by wcota** [comment]
Bom dia!

Isso mesmo. Infelizmente tive de separar em arquivos diferentes para os anos anteriores ao corrente. O arquivo estava passando de 100 MB, limite do GitHub e bloquearia commits futuros.

Ainda devo documentar em algum lugar, foi feito em cima da hora pra evitar problemas futuros.

**Comment by cassianord** [comment]
Perfeito. Muito obrigado pelo seu trabalho!

**Comment by wcota** [comment]
Aliás, adicionei um exemplo em Python com o pandas e glob (pra generalizar, sem precisar colocar manualmente todos os anos) na descrição dos dados https://github.com/wcota/covid19br/blob/master/DESCRIPTION.md#por-munic%C3%ADpios-cases-brazil-citiescsv-cases-brazil-cities-timecsvgz-e-cases-brazil-cities-time_changesonlycsv
