### ISSUE TITLE
Número de casos confirmados por municípios agora só contém os dados de 2022

### ISSUE THREAD

**Issue by edsonportosilva** [wcota/covid19br#77]
Olá Wesley (@wcota),

Estive fazendo uso dos dados desse repositório e notei que, aparentemente, agora o arquivo `cases-brazil-cities-time.csv`  só contém os dados de 2022. Seria possível disponibilizar os dados de 2020 e 2021 novamente?

**Comment by wcota** [comment]
Boa noite! Tive de separar os arquivos de 2020 e 2021 do arquivo principal pois batia o limite de tamanho do GitHub. Eles estão nos arquivos cases-brazil-cities-time_20xx.csv.gz, com xx = 20,21.

Infelizmente, agora tem de juntar os arquivos caso queira a série como antes. No caso do Python já deixei o código pronto na descrição: https://github.com/wcota/covid19br/blob/master/DESCRIPTION.md#por-munic%C3%ADpios-cases-brazil-citiescsv-cases-brazil-cities-timecsvgz-e-cases-brazil-cities-time_changesonlycsv

**Comment by edsonportosilva** [comment]
@wcota, obrigado!
